version: '3.7'

services:
  backend:
    build: ./Backend/simpleapi
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - database

  database:
    build: ./Database
    ports:
      - "5432:5432"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - app-network
    volumes:
      - ./volumes/db:/var/lib/postgresql/data

  httpd:
    build: ./Frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
