version: '3.7'

services:
  adminer:
    image: adminer
    ports:
      - "8081:8080"
    networks:
      - app-network

  backend:
    build: ./Backend/simpleapi
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - database

  database:
    build: ./Database

    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    networks:
      - app-network
    volumes:
      - db:/var/lib/postgresql/data

  httpd:
    build: ./Frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge

volumes:
    db:


