version: '3.7'

services:
  backend:
    build: ./Backend/simpleapi
    ports:
      - "8080:8080"
    networks:
      - app-network
    depends_on:
      - database

  database:
    build: ./Database
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: usr
        POSTGRES_PASSWORD: pwd
        POSTGRES_DB: db
    networks:
      - app-network

  httpd:
    build: ./Frontend
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - backend

networks:
  app-network:
    driver: bridge
